package com.example.slimestore.jpa;

import jakarta.persistence.*;
import lombok.Data;
import java.util.List;

/**
 * Represents a customer order in the SlimeStore.
 * An order contains information about the customer and a list of products.
 */
@Entity
@Data
@Table(name = "orders")
public class Order {

    /**
     * The unique identifier for the order.
     * This ID is automatically generated by the database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * The name of the customer who placed the order.
     */
    private String customerName;

    /**
     * A list of products included in this order.
     * The relationship is a one-to-many from Order to Product.
     * All operations (e.g., cascade, orphan removal) are applied to the products.
     */
    @OneToMany(cascade = CascadeType.ALL, orphanRemoval = true)
    @JoinColumn(name = "order_id")
    private List<Product> products;

    /**
     * An enumeration of the possible statuses for an order.
     * <p>
     * - {@link #ORDER_CREATED}: The order has been successfully created.
     * - {@link #ORDER_DELETED}: The order has been deleted.
     */
    public enum OrderStatus {
        ORDER_CREATED, ORDER_DELETED
    }
}