package com.example.slimestore.jpa;

import jakarta.persistence.*;
import lombok.Data;

/**
 * Represents a single product within an order.
 */
@Entity
@Data
@Table(name = "products")
public class Product {

    /**
     * The unique identifier for the product.
     * This ID is automatically generated by the database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * The name of the product (e.g., "Galaxy Slime").
     */
    private String name;

    /**
     * The quantity of the product in the order.
     */
    private int quantity;

}